# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  #VM Machine Ansible
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "vagrant-debian"
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.100.200"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "1524" # RAM
      vb.cpus = "1" # CPU
    end
    ansible.vm.provision "shell", path: "ansible-setup.sh"
  end

  # Define boxes for web and db
  # VM Machine Web
  config.vm.define "web" do |web|
    web.vm.box = "vagrant-debian"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.100.201"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1524" # RAM
      vb.cpus = "1" # CPU
    end
    web.vm.provision "shell", path: "add-host.sh"
  end 

  # VM Database
  config.vm.define "db" do |db| 
    db.vm.box = "vagrant-alma"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.100.202"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1524" # RAM
      vb.cpus = "1" # CPU
    end
  end 

end 
